;######################################################
;#######################Цвета##########################
;######################################################
[colors]
; Backgrounds / Tones
background = #282828
background-alt = #1d2021
surface = #3c3836
surface-alt = #504945

; Neutrals
foreground = #ebdbb2
foreground-alt = #a89984
disabled = #7c6f64
muted = #a89984
secondary-text = #bdae93
secondary-text-alt = #665c54

; Warm Accents (yellow/orange)
primary = #d79921
primary-light = #fabd2f
warn = #d65d0e
alert = #cc241d
alert-light = #fb4934

; Cool Accents (blue)
info = #458588
info-light = #83a598
underline = #504945
underline-alt = #665c54

; Secondary (green & purple)
success = #98971a
success-light = #b8bb26
active = #b16286
active-light = #d3869b

[bar/main]
font-0 = "JetBrainsMono Nerd Font:size=10;2"
font-1 = "JetBrainsMono Nerd Font:size=16;3"
modules-left = arch-menu xworkspaces
modules-right = calendar wifi-menu
modules-center = pulseaudio xkeyboard
width = 97%
height = 36
offset-x = 1.3%
offset-y = 7
radius = 14

;###############################################
;###################Модули######################
;###############################################
[module/xworkspaces]
type = internal/xworkspaces

format = <label-state>

label-active = 
label-active-foreground = ${colors.primary-light}
label-active-padding = 1

label-occupied = 
label-occupied-foreground = ${colors.info}
label-occupied-padding = 1

label-urgent = 
label-urgent-foreground = ${colors.alert}
label-urgent-padding = 1

label-empty = 
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/arch-menu]
type = custom/text
content = " %{T2} 󰣇%{T-} "
content-foreground = ${colors.primary}
click-left = eww open --toggle my-menu

[module/wifi-menu]
type = custom/text
content = "%{T2}󰤨  %{T-}"
content-foreground = ${colors.primary}
click-left = eww open --toggle wifi-menu

[module/calendar]
type = custom/text
content = "%{T2}󰃭 %{T-}"
content-foreground = ${colors.warn}
click-left = eww open --toggle calendar-menu

[module/pulseaudio]
type = internal/pulseaudio

interval = 1

format-volume = <ramp-volume> <label-volume>
format-volume-padding = 1

label-volume = %percentage%%

label-muted = %{T2}󰖁%{T-} muted
label-muted-foreground = #666

ramp-volume-0 = %{T2}󰕿%{T-}
ramp-volume-1 = %{T2}󰖀%{T-}
ramp-volume-2 = %{T2}󰕾%{T-}



[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = scroll lock

format = <label-indicator> <label-layout>
format-spacing = 1

; Настраиваем конкретно Num Lock (индекс 0)
label-indicator-on-numlock = "%{T2} %{T-}"
label-indicator-on-numlock-foreground = ${colors.primary}
label-indicator-off-numlock = "%{T2} %{T-}"
label-indicator-off-numlock-foreground = ${colors.disabled}

; Настраиваем конкретно Caps Lock (индекс 1)
label-indicator-on-capslock = "%{T2} 󰌎%{T-}"
label-indicator-on-capslock-foreground = ${colors.warn}
label-indicator-off-capslock = "%{T2} 󰌎%{T-}"
label-indicator-off-capslock-foreground = ${colors.disabled}

; Раскладка клавиатуры
label-layout = "%{T1} %layout%%{T-}"
label-layout-foreground = ${colors.foreground}
